### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by somedevreally** [dejablue79/pfsense_VPN_optimizer#1]
Hi,
i installed pfSense-pkg-FauxAPI what next?
can you please explain how to set it up? 
does it have to be installed on pfsense box itself?

thanks

**Comment by dejablue79** [comment]
- After installing pfSense-pkg-FauxAPI can changed the builtin example to a different 
fauxapi-key and fauxapi-secret.

- on your computer, you can clone the repo and add:
ENV host-address=192.168.1.1 #Change it to your pfsense firewall
ENV fauxapi-key=KEY
ENV fauxapi-secret=SECRET
to the Dockerfile (if you want to run it using Docker)
- build and run docker image: https://docs.docker.com/get-started/part2/
or just run the python app.

**Comment by somedevreally** [comment]
ok this is helpful, i'll give it a try
any plans for docker-compose?

**Comment by dejablue79** [comment]
Pushed.

**Comment by somedevreally** [comment]
great, works like a charm. 
can you also add for PIA vpn?
thanks again.

**Comment by dejablue79** [comment]
With PIA you don't have the option to select a specific IP but only use the domain name like:
`de-frankfurt.privateinternetaccess.com`
so there is nothing to optimized but restarting the connection.
