### ISSUE TITLE
different server for multi gateway

### ISSUE THREAD

**Issue by somedevreally** [dejablue79/pfsense_VPN_optimizer#5]
hi,

in nordvpn, when best available server list is 

us1
us2
us3
us4

and if there are 4 VPN client then it set the server as

us1
us2
us2
us2

can we avoid duplicate? 

thanks

**Comment by dejablue79** [comment]
I'll try to reproduce it on my server and fix it.
Thank you for sharing!

**Comment by dejablue79** [comment]
Changed the way servers are being sorted, can you please verify?

**Comment by somedevreally** [comment]
initial testing, looks good
will confirm in few days
thanks 

edit: i was too quick lol, it does set same server multiple times

**Comment by somedevreally** [comment]
```
"nordvpn": {
    "new": {
      "us": [
        "us4634.nordvpn.com", 
        "us5347.nordvpn.com", 
        "us5398.nordvpn.com", 
        "us5398.nordvpn.com"
      ]
    }, 
    "old": {
      "us": [
        "us3854.nordvpn.com", 
        "us5189.nordvpn.com", 
        "us5189.nordvpn.com", 
        "us5189.nordvpn.com"
      ]
    }
  }, 
```

**Comment by somedevreally** [comment]
git pull had issue, i removed everything and built again, looks good....

**Comment by somedevreally** [comment]
"No Need to Update" message does not appear, for Nord when already on same server

**Comment by dejablue79** [comment]
Right! Fixed
Thanks.

**Comment by somedevreally** [comment]
looks good, awesome

**Comment by somedevreally** [comment]
got new error

```
TypeError
TypeError: expected string or bytes-like object

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app.py", line 75, in set_pf_clients
    return jsonify(set_servers())
  File "/usr/src/app/tasks.py", line 131, in set_servers
    if re.findall(r"\d+", vpn_client["server_addr"]):  # Ignore country servers.
  File "/usr/local/lib/python3.8/re.py", line 239, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

**Comment by somedevreally** [comment]
i think `/set` changed server which didnt exist. openvpn client stopped responding, i manually changed the server, than client got connected. but still get the above error on `/set`

**Comment by somedevreally** [comment]
for `/comp` its not getting uk servers
 ```
"uk": {
      "available_servers": {}, 
      "pfsense": [
        "uk1752.nordvpn.com"
      ]
    }, 
```

**Comment by dejablue79** [comment]
I was able to fix the NordVPN servers for UK.
Not sure if the above error is coming from wrong server settings on pfSense or from my code.
I will add some checks.

**Comment by somedevreally** [comment]
instead of uk i see gb as country `
https://api.nordvpn.com/v1/servers/countries`

**Comment by somedevreally** [comment]
latest code works, can get uk servers

**Comment by somedevreally** [comment]
there is an issue with replace 
for example if i change from AT to NL `/replace/nordvpn?loc=at&with=nl`
pfsense openvpn client does get NL server but actual IP stays to previous AT server. if i check on ipleak.net it shows AT server. unless i manually restart the openvpn client.

this could be because openvpn got updated? 
am on pfsense 2.5 and OpenVPN 2.4.9 built on May 1 2020

also if server A is to be replaced, rest of the servers also gets best server

**Comment by dejablue79** [comment]
Ye.. that was a fast and dirty fix.
I’ll look at the replacement of the other clients

**Comment by dejablue79** [comment]
Pushed new code, can you please verify?

**Comment by somedevreally** [comment]
looks good. 
on replace command, only specific server is changed. so thats great. i will test more
also the readability is difficult.

**Comment by somedevreally** [comment]
i still have same issue, on replace command, the openvpn client does get new server, but it does not show up on ipleak.net unless i restart the client.

**Comment by dejablue79** [comment]
I think I got it,
try pulling the new code, and on your pfSense enable:
`openvpn.inc:function openvpn_restart_by_vpnid($mode, $vpnid)`
under `/etc/fauxapi/pfsense_function_calls.txt`

[pfsense_function_calls.txt](https://github.com/ndejong/pfsense_fauxapi/blob/master/pfSense-pkg-FauxAPI/files/etc/fauxapi/pfsense_function_calls.sample.txt)

**Comment by somedevreally** [comment]
it works for "best server" and "replace region" too, cool. thanks you.

also can we go back server list format, as it was earlier? right now its difficult to read.
for `/comp`

`{"nordvpn":{"ee":{"available_servers":{"ee22.nordvpn.com":21,"ee23.nordvpn.com":18,"ee24.nordvpn.com":16,"ee33.nordvpn.com":12,"ee34.nordvpn.com":20,"ee35.nordvpn.com":11,"ee36.nordvpn.com":15,"ee38.nordvpn.com":20,"ee39.nordvpn.com":17,"ee40.nordvpn.com":13},"pfsense":{"ee33.nordvpn.com":12}},"fi":{"available_servers":{"fi101.nordvpn.com":16,"fi104.nordvpn.com":22,"fi105.nordvpn.com":19,"fi108.nordvpn.com":22,"fi114.nordvpn.com":21,"fi115.nordvpn.com":25,"fi117.nordvpn.com":25,"fi118.nordvpn.com":25,"fi88.nordvpn.com":25,"fi89.nordvpn.com":24},"pfsense":{"fi104.nordvpn.com":22}},"fr":{"available_servers":{"fr255.nordvpn.com":15,"fr279.nordvpn.com":15,"fr293.nordvpn.com":15,"fr336.nordvpn.com":16,"fr384.nordvpn.com":16,"fr419.nordvpn.com":15,"fr532.nordvpn.com":12,"fr536.nordvpn.com":16,"fr544.nordvpn.com":16,"fr555.nordvpn.com":16},"pfsense":{"fr446.nordvpn.com":null}},"no":{"available_servers":{"no116.nordvpn.com":11,"no123.nordvpn.com":15,"no128.nordvpn.com":15,"no137.nordvpn.com":11,"no139.nordvpn.com":7,"no150.nordvpn.com":13,"no157.nordvpn.com":14,"no159.nordvpn.com":12,"no161.nordvpn.com":15,"no90.nordvpn.com":15},"pfsense":{"no139.nordvpn.com":7}},"us":{"available_servers":{"us3040.nordvpn.com":17,"us3311.nordvpn.com":17,"us3583.nordvpn.com":17,"us3838.nordvpn.com":17,"us4312.nordvpn.com":15,"us4598.nordvpn.com":17,"us5059.nordvpn.com":16,"us5106.nordvpn.com":16,"us5165.nordvpn.com":15,"us5443.nordvpn.com":17},"pfsense":{"us5339.nordvpn.com":null}}},"protonvpn":{"ee":{"available_servers":{"ee-04.protonvpn.com":36,"ee-05.protonvpn.com":17,"ee-06.protonvpn.com":12,"ee-07.protonvpn.com":20,"ee-08.protonvpn.com":47},"pfsense":{}},"fi":{"available_servers":{"fi-02.protonvpn.com":51,"fi-03.protonvpn.com":38,"fi-04.protonvpn.com":87},"pfsense":{}},"fr":{"available_servers":{"fr-07.protonvpn.com":45,"fr-08.protonvpn.com":52,"fr-09.protonvpn.com":56,"fr-10.protonvpn.com":59,"fr-11.protonvpn.com":56,"fr-12.protonvpn.com":45,"fr-24.protonvpn.com":52,"fr-25.protonvpn.com":59,"fr-26.protonvpn.com":53,"fr-27.protonvpn.com":39,"fr-28.protonvpn.com":27,"fr-32.protonvpn.com":100,"fr-33.protonvpn.com":43,"fr-34.protonvpn.com":42,"fr-35.protonvpn.com":35,"fr-36.protonvpn.com":26},"pfsense":{}},"no":{"available_servers":{"no-02.protonvpn.com":31,"no-03.protonvpn.com":22,"no-04.protonvpn.com":19,"no-08.protonvpn.com":72,"no-09.protonvpn.com":9,"no-10.protonvpn.com":21,"no-11.protonvpn.com":48,"no-12.protonvpn.com":28},"pfsense":{}},"us":{"available_servers":{"us-ny-07.protonvpn.com":57,"us-ny-09.protonvpn.com":66,"us-ny-10.protonvpn.com":43,"us-ny-11.protonvpn.com":53,"us-ny-12.protonvpn.com":54,"us-ny-16.protonvpn.com":77,"us-ny-17.protonvpn.com":81,"us-ny-18.protonvpn.com":74,"us-ny-19.protonvpn.com":86,"us-ny-20.protonvpn.com":66},"pfsense":{}}}}`

**Comment by dejablue79** [comment]
I removed the empty entries, maybe it will help

**Comment by somedevreally** [comment]
awesome, looks good
thanks again
