### ISSUE TITLE
debug mode?

### ISSUE THREAD

**Issue by somedevreally** [dejablue79/pfsense_VPN_optimizer#9]
am using docker image.
How do i turn off debug mode? is it required? should i just ignore?

```
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: xxx-xxx-xxx
```

**Comment by dejablue79** [comment]
Debug is now set to False by default.
in case you would like to turn in on again, just add another env with "DEBUG=true"

**Comment by somedevreally** [comment]
i still see the debug on, i removed and pulled latest image and recreated the container.
i even added DEBUG=false in eve just to check. didn't worked.

thanks

**Comment by dejablue79** [comment]
Right, I had an issue with the docker push automation.
Can you please try now?

**Comment by somedevreally** [comment]
pulled latest build, no luck

**Comment by somedevreally** [comment]
some issue with docker hub, pulled from git everything ok

**Comment by dejablue79** [comment]
Dockerhub should be working as well.
